from django.urls import path
from .views import *


app_name = "web"

urlpatterns = [
    path(
        "",
        HomeView.as_view(),
        name="home"
    ),
    path(
        "neqliyyat/",
        CategoryTransportView.as_view(),
        name="category-transport"
    ),
    path(
        "dashinmaz-emlak/",
        CategoryEstateView.as_view(),
        name="category-estate"
    ),
    path(
        "transport-filters/",
        TransportFiltersView.as_view(),
        name="transport-filters"
    ),
    path(
        "elektronika/",
        CategoryElectronicsView.as_view(),
        name="category-electronics"
    ),
    path(
        "ushaq-alemi/",
        CategoryBabyWorldView.as_view(),
        name="category-baby_world"
    ),
    path(
        "geyim/",
        CategoryClothesView.as_view(),
        name="category-clothes"
    ),
    path(
        "kosmetika-ve-saglamliq/",
        CategoryCosmeticsView.as_view(),
        name="category-cosmetic"
    ),
    path(
        "kosmetika-ve-saglamliq/",
        CategoryCosmeticsView.as_view(),
        name="category-cosmetics"
    ),
    path(
        "ish-elanlari/",
        CategoryJobVacanciesView.as_view(),
        name="category-job_vacancies"
    ),
    path(
        "ev-ve-bag/",
        CategoryHomeGardenView.as_view(),
        name="category-home_garden"
    ),
    path(
        "erzaq/",
        CategoryMealView.as_view(),
        name="category-meal"
    ),
    path(
        "heyvan-ve-bitki/",
        CategoryAnimalsPlantsView.as_view(),
        name="category-animals_plants"
    ),
    path(
        "idman-musiqi-hobbi/",
        CategorySportMusicHobbyView.as_view(),
        name="category-sport_music_hobby"
    ),
    path(
        "diger/",
        CategoryOthersView.as_view(),
        name="category-others"
    ),
    path(
        "xidmetler/",
        CategoryServicesView.as_view(),
        name="category-services"
    ),
    path(
        "elektronika/telefonlar/",
        SubcategoryTelephonesView.as_view(),
        name="subcategory-telephones"
    )
]